defaults:
  - datasets: ???
  - experiments: ???
  - _self_
hydra:
  sweeper:
    params:
      datasets: translated_it_en,translated_it_es
      experiments: turbo35_fuzzy_3ex, turbo35_random_3ex, turbo35_label_3ex