dataset: translated_big
train: data/processed/translated/translated-big-it-es-train.csv
test: data/processed/translated/translated-big-it-es-test.csv
dev: data/processed/translated/translated-big-it-es-dev.csv
src_lan: it
trg_lan: es
sep: ','
encoding: utf-8
languageA : Italian
languageB : Spanish