dataset: translated
train: data/processed/translated/translated-it-en-train.csv
test: data/processed/translated/translated-it-en-test.csv
emb_src: data/processed/translated/translated-it-en-dev-embedding_it.pt
dev: data/processed/translated/translated-it-en-dev.csv
src_lan: it
trg_lan: en
sep: ','
encoding: utf-8
prefix : "Translate from Italian to English:"
languageA : Italian
languageB : English