dataset: translated
test: data/processed/translated/translated-it-en-test.csv
emb_src: data/processed/translated/translated-it-en-dev-embedding_it.pt
dev: data/processed/translated/translated-it-en-dev.csv
src_lan: it
trg_lan: en